//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pvv_2210900085.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sach
    {
        public int masach { get; set; }
        public string tensach { get; set; }
        public Nullable<int> sotrang { get; set; }
        public Nullable<int> namxb { get; set; }
        public string tentacgia { get; set; }
        public Nullable<int> manxb { get; set; }
    
        public virtual nhaxuatban nhaxuatban { get; set; }
    }
}
